env:
  browser: true
  es6: true
  jest: true
  react-native/react-native: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - react-native 
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - warn
  no-unused-vars:
    - warn
  comma-spacing:
    - error
    - after: true
  key-spacing:
    - error
    - afterColon: true
  react/jsx-uses-react:
    - error
  react/jsx-uses-vars:
    - error
  object-curly-spacing:
    - error
    - never
